---
title: "Supply Chain Management Project"
author: "Elizabeth Anajovich, Celton Do, Ketsaraporn Kaewkhiaolueang, Evan Pinckard, and Bryce Samwel"
date: "10/22/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, libraries, include=FALSE}
library(gridExtra)
library (tufte)
library (magrittr, quietly = TRUE)
suppressPackageStartupMessages(
  library(dplyr, quietly = TRUE))
suppressPackageStartupMessages(
  library (ROI, quietly = TRUE))
library(ROI.plugin.glpk, quietly = TRUE)
library (ompr, quietly = TRUE)
library(ompr.roi, quietly = TRUE)
```

$$\text{Building Type and Location Optimization Equations}\\
\text{Maximize the following,}\\
\text{ where }C\text{ is the total Capacity of buildings, }
i\text{ represents the subregions, and }
j \text{ is the Building types. }\\
\sum_{i=1}^{15}\sum_{j=1}^{5} C_{j} * x_{i,j}\\
\text{  Given the following constraints, where }R
\text{ is the Regional building limits, and }S\text{ is the Subregion limits }\\
\sum_{i=1}^{4} x_{i,1} \leq R_1,\; 
\sum_{i=5}^{7} x_{i,2} \leq R_2,\;
\sum_{i=8}^{12} x_{i,3} \leq R_3,\;  
\sum_{i=13}^{13} x_{i,4} \leq R_4,\;
\sum_{i=14}^{15} x_{i,5} \leq R_5,\;
\text{ and } \sum_{j=1}^{5} x_{i,j} \leq S_i \;\forall \; i\\
\text{And there are also Building Type limits, represented by }B\\ 
\sum_{i=1}^{15} x_{i,j} \leq B_j \; \forall \; j\\ $$


```{r model}
NSubregions <- 15
NBuildingTypes <- 5

StartingCapacities <- c(-20,15,2,5,-1,4,-3,20,4,-5,8,-3,2,1,4)

S <- c(2,3,4,3,
       3,2,3,
       2,5,6,5,5,
       2,
       2,3) #Sub-region Limits

R <- c(5,10,1,2,4) #Region Limits

B <- c(4,3,2,4,2) #Building Type LImits

C <- c(20,16,14,10,25) #Capacity per Building Type

model <- MIPModel() %>%
  add_variable(x[i,j], type = "integer",
               i=1:NSubregions,
               j=1:NBuildingTypes, lb=0)%>%
  
  set_objective(sum_expr(C[j]*x[i,j],
                         j=1:NBuildingTypes,
                         i=1:NSubregions), "max")%>%
  
  add_constraint(sum_expr(x[i,1],i=1:4) <= R[1])%>%
  add_constraint(sum_expr(x[i,2],i=5:7) <= R[2])%>%
  add_constraint(sum_expr(x[i,3],i=8:12) <= R[3])%>%
  add_constraint(x[13,4] <= R[4])%>%
  add_constraint(sum_expr(x[i,5],i=14:15) <= R[5])%>%
    #Limit buildings per region (NOT WORKING)
  
  add_constraint(sum_expr(x[i,j], j=1:NBuildingTypes) <= S[i],
                  #Limit number of buildings per sub-region
                 i=1:NSubregions)%>% 
    
  add_constraint(sum_expr(x[i,j], i=1:NSubregions) <= B[j],
                  #Limit number of building types
                 j=1:NBuildingTypes)%>% 
  
  
  
 # add_constraint(sum_expr(C[j]*x[i,j], j=1:NBuildingTypes) >= -StartingCapacities[i], i=1:NSubregions)%>%
                  #Ensure Capacities >= 0
                  
    
  
  solve_model(with_ROI(solver = "glpk"))
model

results <- get_solution (model, x[i,j])
resultstable <- matrix(results[,4],ncol=5)
resultstable


AdditionalCapacities <- rep(0, NSubregions)
for (n in 1:75){
  AdditionalCapacities[results[n,2]] <- AdditionalCapacities[results[n,2]]+
    results[n,4]*C[results[n,3]]
}

FinalCapacities <- StartingCapacities + AdditionalCapacities

FinalCapacities <- cbind(StartingCapacities,FinalCapacities)
grid.table(FinalCapacities)
```